# Generated by Django 4.2 on 2023-05-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('coin', models.IntegerField()),
                ('best_score', models.IntegerField()),
            ],
            options={
                'db_table': 'player_info',
                'managed': False,
            },
        ),
    ]
