# Generated by Django 4.2 on 2023-05-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_score', '0002_player_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('item1', models.IntegerField()),
                ('item2', models.IntegerField()),
                ('item3', models.IntegerField()),
                ('item4', models.IntegerField()),
                ('item5', models.IntegerField()),
            ],
            options={
                'db_table': 'player_shop',
                'managed': False,
            },
        ),
    ]
