
player_nicknames = ['Bakugan74', 'hsbulla', 
                    'Anastasia','Sanoo',
                    'Vethre','Qucananie',
                    'Jarehetip','Ftelomar',
                    'Wynelt','Ieam',
                    'Randiani','Inazeoril',
                    'Rol','Eri',
                    'Ken','Vase',
                    'Hash','Laial',
                    'Enhind','Get12',
                    'Psta','Serokaoo',
                    'Uretaly','Orje',
                    'Crerorane','Dliadel',
                    'Qujorl','Malellari',
                    'Ncaran','Kel',
                    'Farapari','Gariru',
                    'Uriliaro','Elar',
                    'Waext','Villeyar',
                    'Samespaha','Rcluriry',
                    'Melari','Umanllivo',
                    'Jamuc','Fadeedo',
                    'Pafi','Gaca', 
                    'shyddle']